name: scp files
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.AIRFLOW_PEM }}
        port: 22
        source: "docker-compose.yml,run.sh"
        target: "files"

  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands
      uses: appleboy/ssh-action@master

      with:
        host: ${{ secrets.HOST }}
        username: ubuntu
        key: ${{ secrets.AIRFLOW_PEM }}
        port: 22
        script: |
          cd files/
          chmod 700 run.sh
          sudo docker-compose down
          ./run.sh

      # env:
      #     AIRFLOW_PEM: ${{ secrets.AIRFLOW_PEM }}
      #     POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE_DEV }}
      #     POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_DATABASE_DEV }}
      #     POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD_DEV }}
      #     AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
      #     AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
      #     AIRFLOW_EMAIL: ${{ secrets.AIRFLOW_EMAIL }}
