name: develop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: before_script
      run: |
        sudo apt-get update
        sudo apt-get install gettext-base
        eval $(ssh-agent -s)
        echo "$AIRFLOW_PEM" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        envsubst < docker-compose.yaml > docker-compose.yml
        scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@${{ secrets.HOST }}:docker-compose.yaml
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.HOST }} 'bash -s' < run.sh
      env:
        AIRFLOW_PEM: ${{ secrets.AIRFLOW_PEM }}
        POSTGRESQL_DATABASE: ${{ secrets.POSTGRESQL_DATABASE_DEV }}
        POSTGRESQL_USERNAME: ${{ secrets.POSTGRESQL_DATABASE_DEV }}
        POSTGRESQL_PASSWORD: ${{ secrets.POSTGRESQL_PASSWORD_DEV }}
        AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
        AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
        AIRFLOW_EMAIL: ${{ secrets.AIRFLOW_EMAIL }}
